name: Generate Gradle Wrapper

on:
  workflow_dispatch:

jobs:
  wrapper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Generate Wrapper
        run: gradle wrapper --gradle-version 8.7

      - name: Upload Wrapper Files
        uses: actions/upload-artifact@v4
        with:
          name: gradle-wrapper-files
          path: |
            gradlew
            gradlew.bat
            gradle/wrapper/